### **CONSTRAINTS**

**Definition:**  
A **constraint** in SQL is a rule that limits the type of data that can be inserted into a table. Constraints are used to enforce the integrity of the data in the database. They ensure that the data is accurate, valid, and consistent.

**Types of Constraints:**
1. **PRIMARY KEY**
2. **FOREIGN KEY**
3. **UNIQUE**
4. **NOT NULL**
5. **CHECK**
6. **DEFAULT**

---

### **PRIMARY KEY**

**Definition:**  
A **PRIMARY KEY** constraint uniquely identifies each record in a database table. A table can have only one primary key, and it must contain unique values. The primary key column cannot have `NULL` values.

**Characteristics of a PRIMARY KEY:**
- Uniqueness: No two rows can have the same value in the primary key column(s).
- Non-NULL: The primary key column(s) must always contain values.
- Each table can have only one primary key, which can be a single or a combination of columns (composite primary key).

**Syntax to Create a Primary Key:**
```sql
CREATE TABLE table_name (
  column_name datatype,
  ...
  CONSTRAINT constraint_name PRIMARY KEY (column_name);
);
```

**Example using the **Student Database**:**

In our **Students** table, we can define `StudentID` as the primary key.

```sql
CREATE TABLE Students (
  StudentID INT,
  Name VARCHAR(50),
  Age INT,
  Gender CHAR(1),
  City VARCHAR(50),
  CONSTRAINT PK_Student PRIMARY KEY (StudentID)
);
```

**Explanation:**  
- `StudentID` is the primary key, and each student will have a unique `StudentID`.
- We cannot insert two students with the same `StudentID` or leave the `StudentID` column as `NULL`.

**Inserting Data into the Students Table:**
```sql
INSERT INTO Students (StudentID, Name, Age, Gender, City)
VALUES (1, 'Alice', 21, 'F', 'Dallas');
```

If you attempt to insert a record with a duplicate `StudentID`, SQL will return an error.

---

### **FOREIGN KEY**

**Definition:**  
A **FOREIGN KEY** is a column (or a set of columns) in one table that references the **PRIMARY KEY** or **UNIQUE KEY** of another table. The foreign key constraint ensures that the value in the foreign key column matches an existing value in the referenced table, ensuring referential integrity between the two tables.

**Characteristics of a FOREIGN KEY:**
- Ensures that a value in the foreign key column corresponds to an existing value in the referenced table.
- A foreign key can accept `NULL` values unless explicitly restricted.
- Foreign keys are used to establish relationships between tables (e.g., one-to-many, many-to-many).

**Syntax to Create a Foreign Key:**
```sql
CREATE TABLE table_name (
  column_name datatype,
  ...
  CONSTRAINT constraint_name FOREIGN KEY (column_name) REFERENCES referenced_table(referenced_column)
);
```

**Example using the **Student Database**:**

In the **Enrollments** table, `StudentID` is a foreign key that references the `StudentID` column in the `Students` table, and `CourseID` is a foreign key that references the `CourseID` column in the `Courses` table.

```sql
CREATE TABLE Enrollments (
  EnrollmentID INT,
  StudentID INT,
  CourseID INT,
  EnrollmentDate DATE,
  CONSTRAINT PK_Enrollment PRIMARY KEY (EnrollmentID),
  CONSTRAINT FK_Student FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
  CONSTRAINT FK_Course FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);
```

**Explanation:**
- `StudentID` in the `Enrollments` table is a foreign key referencing `StudentID` in the `Students` table.
- `CourseID` in the `Enrollments` table is a foreign key referencing `CourseID` in the `Courses` table.

**Foreign Key Operations:**

1. **ON DELETE CASCADE:** When a referenced record in the parent table is deleted, all corresponding records in the child table are automatically deleted.
   ```sql
   CONSTRAINT FK_Student FOREIGN KEY (StudentID) 
   REFERENCES Students(StudentID)
   ON DELETE CASCADE;
   ```

2. **ON UPDATE CASCADE:** When a referenced record in the parent table is updated, the corresponding foreign key values in the child table are also updated automatically.
   ```sql
   CONSTRAINT FK_Student FOREIGN KEY (StudentID)
   REFERENCES Students(StudentID)
   ON UPDATE CASCADE;
   ```

3. **ON DELETE SET NULL:** When a referenced record is deleted, the foreign key in the child table is set to `NULL`.
   ```sql
   CONSTRAINT FK_Student FOREIGN KEY (StudentID)
   REFERENCES Students(StudentID)
   ON DELETE SET NULL;
   ```

---

### **Example of Inserting Data with Foreign Key Constraints:**

1. **Insert a student into the `Students` table:**
   ```sql
   INSERT INTO Students (StudentID, Name, Age, Gender, City)
   VALUES (1, 'Alice', 21, 'F', 'Dallas');
   ```

2. **Insert a course into the `Courses` table:**
   ```sql
   INSERT INTO Courses (CourseID, CourseName, Credits)
   VALUES (1, 'Math 101', 3);
   ```

3. **Insert an enrollment record into the `Enrollments` table:**
   ```sql
   INSERT INTO Enrollments (EnrollmentID, StudentID, CourseID, EnrollmentDate)
   VALUES (1, 1, 1, '2024-01-15');
   ```

### Foreign Key Violations:
- If you try to insert a record into the `Enrollments` table with a `StudentID` that doesn't exist in the `Students` table, SQL will return an error:
  ```sql
  INSERT INTO Enrollments (EnrollmentID, StudentID, CourseID, EnrollmentDate)
  VALUES (2, 999, 1, '2024-01-20');
  -- Error: 999 is not a valid StudentID in the Students table
  ```

---

### **Summary of Primary Key and Foreign Key:**

1. **PRIMARY KEY:**
   - Ensures that each record in a table is unique.
   - Cannot contain `NULL` values.
   - There can only be one primary key in a table.

2. **FOREIGN KEY:**
   - Ensures referential integrity by linking one table’s column to another table’s primary key.
   - Can contain `NULL` values (unless restricted).
   - You can have multiple foreign keys in a table.

---

Let me know if you'd like to explore more about constraints, or if you’d like to proceed to the next topic!