### **TCL (Transaction Control Language)**  

TCL commands manage transactions in a database. A transaction is a sequence of SQL operations that are executed as a single unit, ensuring data integrity. The most common TCL commands are:

1. **COMMIT**: Saves all the changes made during the current transaction.  
2. **ROLLBACK**: Reverts changes made during the current transaction.  
3. **SAVEPOINT**: Sets a point within a transaction to which you can later roll back.  
4. **SET TRANSACTION**: Defines properties for the current transaction.

---

### **1. COMMIT**  
Saves all the changes made by DML statements during the transaction.

#### **Syntax**:  
```sql
COMMIT;
```

#### **Example**:  

```sql
BEGIN TRANSACTION;

INSERT INTO Students (StudentID, Name, Age, City)
VALUES (5, 'Eve', 23, 'Miami');

UPDATE Students
SET Age = 24
WHERE Name = 'Eve';

COMMIT;
```

After `COMMIT`, all changes are permanently saved to the database.

---

### **2. ROLLBACK**  
Undoes changes made during the current transaction before a `COMMIT` is issued.

#### **Syntax**:  
```sql
ROLLBACK;
```

#### **Example**:  

```sql
BEGIN TRANSACTION;

DELETE FROM Students
WHERE Name = 'Alice';

-- An error occurs or a decision is made to cancel the operation
ROLLBACK;
```

After `ROLLBACK`, the deletion of Alice's record is undone.

---

### **3. SAVEPOINT**  
Sets a save point within a transaction, allowing partial rollbacks to that specific point.

#### **Syntax**:  
```sql
SAVEPOINT savepoint_name;
```

#### **Example**:  

```sql
BEGIN TRANSACTION;

INSERT INTO Students (StudentID, Name, Age, City)
VALUES (6, 'Frank', 21, 'Dallas');

SAVEPOINT Savepoint1;

UPDATE Students
SET City = 'Austin'
WHERE Name = 'Frank';

ROLLBACK TO Savepoint1;

COMMIT;
```

Here, the update to change Frank's city to `Austin` is undone, but the insertion of Frank is saved because of the rollback to `Savepoint1`.

---

### **4. SET TRANSACTION**  
Defines the properties of a transaction, such as its isolation level.

#### **Syntax**:  
```sql
SET TRANSACTION [READ WRITE | READ ONLY] [ISOLATION LEVEL isolation_level];
```

#### **Example**:  

```sql
SET TRANSACTION READ WRITE ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;

INSERT INTO Students (StudentID, Name, Age, City)
VALUES (7, 'Grace', 22, 'Houston');

COMMIT;
```

---

### **Key Points**  

1. **Transactions**: A transaction begins with a `BEGIN TRANSACTION` (or starts implicitly) and ends with a `COMMIT` or `ROLLBACK`.  
2. **Atomicity**: Transactions ensure that all operations are completed successfully, or none of them are applied.  
3. **SAVEPOINT Advantage**: Useful for dividing large transactions into smaller, manageable parts.  
4. **Isolation Levels**: Ensure consistency when multiple transactions occur concurrently.

Let me know if you'd like more examples or detailed use cases!